server:
  port: ${SERVER_PORT}

spring:
  main:
    web-application-type: servlet
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      path: ${H2_CONSOLE_PATH:}
      settings:
        trace: false
        web-allow-others: false

# ==================================================================
# API Doc / Swagger
# ==================================================================

spring-doc:
  pathsToMatch: /api/**
  show-actuator: true
  swagger-ui.enabled: ${SWAGGER_ENABLED}

  api-docs:
    path: ${API_DOCS_PATH}
